import Head from 'next/head';
import Tabela from '../components/lista';
import { PacientsProvider } from '../hooks/usePacients';
import Busca from '../components/busca';
import Reset from '../components/reset';


const Home = () => {
	return (
		<div>
			<Head>
				<title>Fetcher</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.svg' />
			</Head>
			<h1>Home</h1>
			<PacientsProvider>
				<Tabela/>
				<Busca/>
				<Reset/>
			</PacientsProvider>
		</div>
	);
};

export default Home;
